### ISSUE TITLE
Supernet training and tuning

### ISSUE THREAD

**Issue by pawopawo** [megvii-model/DetNAS#1]
Thanks for your excellent work!

I have not found how to pretrain supernet in ImageNet and tuning supernet in COCO, [here](https://github.com/megvii-model/ShuffleNet-Series) is no supernet training, only the training of the searched network.

**Comment by yukang2017** [comment]
Hi,
for training the supernet on COCO, take 300M FPN  models for example,
you can just run
`bash scripts/run_detnas_coco_fpn_300M_search.sh`
and refer to `configs/e2e_faster_rcnn_DETNAS_COCO_FPN_300M_search.yaml` for details.
(The '_search' tail means for supernet training.)

For training the supernet on ImageNet, I would pull request to my colleague who is in charge of the [ImageNet project](https://github.com/megvii-model/SinglePathOneShot). It will not cost too long. Thanks!

**Comment by yukang2017** [comment]
Hi, for training the supernet on ImageNet, you can find it [here](https://github.com/megvii-model/DetNAS/tree/master/Supernet-ImageNet). This part is inherited from the [ImageNet project](https://github.com/megvii-model/SinglePathOneShot), where you can find more details.

Please feel free to reopen the issue if there are any other questions.

**Comment by uname0x96** [comment]
@yukang2017 Can I train with my custom dataset? And I just have only 1 or maximum is 2 cards RTX-2080Ti so it enough for the train?
