### ISSUE TITLE
Training supernet is hard to converge.

### ISSUE THREAD

**Issue by huizhang0110** [megvii-model/DetNAS#10]
Hello,
I find that the supernet training process is hard to converge. Would you mind providing us log files?

**Comment by yukang2017** [comment]
Hi,

If the supernet training on COCO has issues, I guess the reasons might from:
(1) The sync bn is not installed in the right way.
(2) The pre-trained model is not loaded.

The training log is here:
[SuperNet-COCO-FPN300M-log.txt](https://github.com/megvii-model/DetNAS/files/3992274/SuperNet-COCO-FPN300M-log.txt)

The trained supernet model is here:
https://drive.google.com/open?id=1RPalJivbLeAAu7cLETrl45U6qEHQCX0K

**Comment by yukang2017** [comment]
If you have any further issues, please feel free to reopen this issue. You can also email me directly.
