### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by pipi2020** [megvii-model/DetNAS#11]
could you please send the demo code so that i can run it to test the trained model with visualization? thank U

**Comment by yukang2017** [comment]
Hi,

A as this project is based on [maskrcnn benchmark](https://github.com/facebookresearch/maskrcnn-benchmark), you can refer to it for visualization.

You can find the solutions in the following:
https://github.com/facebookresearch/maskrcnn-benchmark/pull/138
https://github.com/facebookresearch/maskrcnn-benchmark/issues/374
