### ISSUE TITLE
{'status': 'failure'} Traceback (most recent call last):   File "distributed_arch_search/search.py", line 138, in sync_candidates     info['acc']=res['acc'] KeyError: 'acc' try to get 1499-1579437134.2298317

### ISSUE THREAD

**Issue by lmomoy** [megvii-model/DetNAS#15]
when I search the network with my data, I meet this problem:

{'status': 'failure'}
Traceback (most recent call last):
  File "distributed_arch_search/search.py", line 138, in sync_candidates
    info['acc']=res['acc']
KeyError: 'acc'

**Comment by yukang2017** [comment]
This error usually appears when the model does not finish the evaluation on the validation set. You can try `tools/test_net.py` first to ensure that there have no issues in the evaluation process.

**Comment by betterhalfwzm** [comment]
> This error usually appears when the model does not finish the evaluation on the validation set. You can try `tools/test_net.py` first to ensure that there have no issues in the evaluation process.

Can you share search log?I have the same issue on the coco.Thx.

**Comment by yukang2017** [comment]
This is the log of one search running [Google Drive](https://drive.google.com/open?id=1PXtt9zY6u-Viz4PBCuBwaQDXI2L41LIg).
