### ISSUE TITLE
Step5 evaluation result very low

### ISSUE THREAD

**Issue by barleyyuan** [megvii-model/DetNAS#16]
Have you ever had a situation where in Step 5 (model evaluation)，all the models searched were evaluated very low, that is, the AP value? I trained the supernet both on my own dataset and COCO dataset,  but all searched models had a very low AP during step 5, close to 0. However, when I evaluated the model using the script 'tools/test_net.py', the AP was greater than 0.6.

**Comment by betterhalfwzm** [comment]
> Have you ever had a situation where in Step 5 (model evaluation)，all the models searched were evaluated very low, that is, the AP value? I trained the supernet both on my own dataset and COCO dataset, but all searched models had a very low AP during step 5, close to 0. However, when I evaluated the model using the script 'tools/test_net.py', the AP was greater than 0.6.

+1.do you solve it?

**Comment by barleyyuan** [comment]
> > Have you ever had a situation where in Step 5 (model evaluation)，all the models searched were evaluated very low, that is, the AP value? I trained the supernet both on my own dataset and COCO dataset, but all searched models had a very low AP during step 5, close to 0. However, when I evaluated the model using the script 'tools/test_net.py', the AP was greater than 0.6.
> 
> +1.do you solve it?

Yes, I have solved it. I found the bug is that 'cfg' is not the newest config in some scripts but the default config. You can modify the bug by these steps below. If you find a better solution, please let me know.
1. In maskrcnn_benchmark/modeling/backbone/shuffle_blocks.py, comment 'from maskrcnn_benchmark.config import cfg' and add 'cfg' as a parameter for 'ShuffleNetV2BlockSearched';
2. In maskrcnn_benchmark/pytorch_distributed_syncbn/syncbn.py, do same as above for 'DistributedSyncBN'.

**Comment by betterhalfwzm** [comment]
> > > Have you ever had a situation where in Step 5 (model evaluation)，all the models searched were evaluated very low, that is, the AP value? I trained the supernet both on my own dataset and COCO dataset, but all searched models had a very low AP during step 5, close to 0. However, when I evaluated the model using the script 'tools/test_net.py', the AP was greater than 0.6.
> > 
> > 
> > +1.do you solve it?
> 
> Yes, I have solved it. I found the bug is that 'cfg' is not the newest config in some scripts but the default config. You can modify the bug by these steps below. If you find a better solution, please let me know.
> 
> 1. In maskrcnn_benchmark/modeling/backbone/shuffle_blocks.py, comment 'from maskrcnn_benchmark.config import cfg' and add 'cfg' as a parameter for 'ShuffleNetV2BlockSearched';
> 2. In maskrcnn_benchmark/pytorch_distributed_syncbn/syncbn.py, do same as above for 'DistributedSyncBN'.

Can you share your code? I'm a little confused.Thx!!  @barleyyuan

**Comment by barleyyuan** [comment]
> > > > Have you ever had a situation where in Step 5 (model evaluation)，all the models searched were evaluated very low, that is, the AP value? I trained the supernet both on my own dataset and COCO dataset, but all searched models had a very low AP during step 5, close to 0. However, when I evaluated the model using the script 'tools/test_net.py', the AP was greater than 0.6.
> > > 
> > > 
> > > +1.do you solve it?
> > 
> > 
> > Yes, I have solved it. I found the bug is that 'cfg' is not the newest config in some scripts but the default config. You can modify the bug by these steps below. If you find a better solution, please let me know.
> > 
> > 1. In maskrcnn_benchmark/modeling/backbone/shuffle_blocks.py, comment 'from maskrcnn_benchmark.config import cfg' and add 'cfg' as a parameter for 'ShuffleNetV2BlockSearched';
> > 2. In maskrcnn_benchmark/pytorch_distributed_syncbn/syncbn.py, do same as above for 'DistributedSyncBN'.
> 
> Can you share your code? I'm a little confused.Thx!! @barleyyuan

A simpler way:
1. In maskrcnn_benchmark/config/defaults.py Line 102 -->
_C.MODEL.BACKBONE.CHANNEL_SHUFFLE_METHOD = 1
2. In maskrcnn_benchmark/pytorch_distributed_syncbn.py Line 94 -->
    def __init__(self, num_features, eps=1e-5, momentum=0.1, affine=True,

Hope it helpful for you!

**Comment by barleyyuan** [comment]
> > > > Have you ever had a situation where in Step 5 (model evaluation)，all the models searched were evaluated very low, that is, the AP value? I trained the supernet both on my own dataset and COCO dataset, but all searched models had a very low AP during step 5, close to 0. However, when I evaluated the model using the script 'tools/test_net.py', the AP was greater than 0.6.
> > > 
> > > 
> > > +1.do you solve it?
> > 
> > 
> > Yes, I have solved it. I found the bug is that 'cfg' is not the newest config in some scripts but the default config. You can modify the bug by these steps below. If you find a better solution, please let me know.
> > 
> > 1. In maskrcnn_benchmark/modeling/backbone/shuffle_blocks.py, comment 'from maskrcnn_benchmark.config import cfg' and add 'cfg' as a parameter for 'ShuffleNetV2BlockSearched';
> > 2. In maskrcnn_benchmark/pytorch_distributed_syncbn/syncbn.py, do same as above for 'DistributedSyncBN'.
> 
> Can you share your code? I'm a little confused.Thx!! @barleyyuan

A simpler way:

    In maskrcnn_benchmark/config/defaults.py Line 102 
  _C.MODEL.BACKBONE.CHANNEL_SHUFFLE_METHOD = 1
       -->
  _C.MODEL.BACKBONE.CHANNEL_SHUFFLE_METHOD = 1
    In maskrcnn_benchmark/pytorch_distributed_syncbn.py Line 94 
  def init(self, num_features, eps=1e-5, momentum=0.01, affine=True,
     -->
  def init(self, num_features, eps=1e-5, momentum=0.1, affine=True,

Hope it helpful for you!

**Comment by yuyijie1995** [comment]
@betterhalfwzm Have you solved the problem?
