### ISSUE TITLE
Why search cfg.SOLVER.IMS_PER_BATCH = 8 ?

### ISSUE THREAD

**Issue by betterhalfwzm** [megvii-model/DetNAS#17]
cfg.SOLVER.IMS_PER_BATCH = 8
    cfg.SOLVER.MAX_ITER = 88888888
    cfg.TEST.IMS_PER_BATCH = ngpus_per_node
when I change it, training is very slow.
And when i  start more than one run_server.sh: ERROR RuntimeError: Address already in use.
Thx!!!!

**Comment by barleyyuan** [comment]
1. The number of IMS_PER_BATCH depands on your GPU memory.
2. Set different "master_port"  for different servers, then they can run at the same time.

**Comment by betterhalfwzm** [comment]
> 1. The number of IMS_PER_BATCH depands on your GPU memory.
> 2. Set different "master_port"  for different servers, then they can run at the same time.

Thx！！！！
