### ISSUE TITLE
PIXEL_MEAN:[0., 0., 0.]?

### ISSUE THREAD

**Issue by Jacobew** [megvii-model/DetNAS#18]
Hi, thanks for your excellent work!
I've found PIXEL_MEAN:[0., 0., 0.] in DetNAS configuration, which is different from the original maskrcnn-benchmark setting and is somewhat counterintuitive. 
Could you please explain it?

**Comment by yukang2017** [comment]
Hi Jacobew,

Sorry for the late reply. It is because we do not subtract pixel mean when training the pre-training models. You can use the original PIXEL_MEAN maskrcnn-benchmark if you also do so in the pre-training stage. It makes little performance difference.
