### ISSUE TITLE
if 'caption' in anns[0]: IndexError: list index out of range

### ISSUE THREAD

**Issue by vanessasidrim** [megvii-model/DetNAS#21]
In step 5 (model evaluation) when calling the function **evaluete_prediction_coco( )**, I get an error. Within this function, a value is assigned to a **coco_dt** variable by returning the call **coco_get.loadRes(coco_result)**, but at this moment the error **if 'caption' in anns [0] is displayed: IndexError: list index out of range**

**Comment by yukang2017** [comment]
This is a about the version of maskrcnn-benchmark and pytorch. Please refer to [#1182](https://github.com/facebookresearch/maskrcnn-benchmark/issues/1182) in maskrcnn-benchmark.

**Comment by BaoChunxiao** [comment]
This is because **coco_results[iou_type]** is an empty list, means model don't inference any BBOX.
