### ISSUE TITLE
Training model in Google Cloud

### ISSUE THREAD

**Issue by alfjesus3** [megvii-model/DetNAS#25]
I'm interested in your approach, and I would like to train the model in a Google cloud virtual machine.
Can you release a tutorial on how to install/setup the model in Google cloud VM?
Or provide any further resources on how to proceed in that situation?
Thank you for you attention to this situation.

**Comment by yukang2017** [comment]
Dear alfjesus3, I am sorry that I have no experience on Google cloud VM. You might try to install it and post questions here if you meet any issues during installation. Thanks.

**Comment by alfjesus3** [comment]
Thank you for the reply. I was able to access the cluster of my university therefore I will use the tutorial you provided. Just a question, if I want to train the Model ImageNet using 4 GPUs, what changes to the nn.DataParallel() model in the train.py do I need to perform ?

**Comment by alfjesus3** [comment]
I managed to have access to the cluster in my University so I don't require to perform the setup on Google Cloud.
