### ISSUE TITLE
error：command '/usr/bin/nvcc'  failed with exit status1

### ISSUE THREAD

**Issue by buzhidaoshenme** [megvii-model/DetNAS#26]
I ran bash config.sh, but error occurred during the installation of maskrcnn_benchmark.
My environment: cuda=10.1, gcc=7.5 .

**Comment by buzhidaoshenme** [comment]
I set cuda version and gcc vision to 9.2 and 5.4, failed again.

**Comment by yukang2017** [comment]
Sorry for the late reply. Wish that you have already solved this issue. If not, please reopen this issue and paste the error log. I will help here. And you can also refer to https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md.
