### ISSUE TITLE
RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.

### ISSUE THREAD

**Issue by yuyijie1995** [megvii-model/DetNAS#31]
this error happened, can you give me some suggestions?

**Comment by yuyijie1995** [comment]
Do you have no syncbn imagenet pretrain weight

**Comment by huqianqian123** [comment]
I have met the same problem when finetune the model with coco datasets, how to solve it ?
