### ISSUE TITLE
Training of 300M didn't seem to meet the expectation

### ISSUE THREAD

**Issue by soysc** [megvii-model/DetNAS#33]
After training on 300M model, got ![image](https://user-images.githubusercontent.com/54491803/115984981-4b523900-a5dc-11eb-9464-82982f3a7e59.png) finally
is there anything wrong with my training?
here's the log file:
[log.txt](https://github.com/megvii-model/DetNAS/files/6371460/log.txt)

**Comment by yukang2017** [comment]
Sorry for the late reply. I think the reason might come from the number of gpus (2) you used is not enough, which leads to a small batch size. We can get normal results when training with 4 gpus or 8 gpus.
