### ISSUE TITLE
Pre-train time

### ISSUE THREAD

**Issue by z740695564** [megvii-model/DetNAS#5]
Hello, when running your pre-train code, it finds iteration once, which takes an average of 1.3 seconds, then 300k iteration is expected to take at least 108 hours (4.5 days), but your paper says 1.5 days, my experimental environment is as follows:
Hardware Configuration:
1, GPU: 8 * Tesla V100-PCIE
2, CPU: 88 * virtual core
Software configuration:
1, pytorch==1.0.1.post2
2, batchsize=1024
3, DataLoader: num_workers=80
4, datasets: Imagenet
Is it that you are using other acceleration strategies?

**Comment by ytoon** [comment]
How long is the data time per iteration (process time)? Our data process has been optimized, so the data time is negligible.

**Comment by buzhidaoshenme** [comment]
> How long is the data time per iteration (process time)? Our data process has been optimized, so the data time is negligible.

Hi~  When I tried to install DetNAS , I got the following compilation error.
"error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1".
Could you please post the PyTorch version, gcc version and cuda version that you used?  It maybe helpful to me. Thank you~

**Comment by yukang2017** [comment]
Sorry for the late reply. We previously use torch==1.3.0 and CUDA=10.2.
