### ISSUE TITLE
COCO training

### ISSUE THREAD

**Issue by betterhalfwzm** [megvii-model/DetNAS#7]
Thanks for your excellent work!

 How much time this step?
COCO training
bash scripts/run_detnas_coco_fpn_300M_search.sh
('-search' in cfg.MODEL.BACKBONE.CONV_BODY is to distinguish supernet training from single model.)
AND
only after training coco, can train search backbone? Can you offer Supernet coco fine-tuning model?

**Comment by yukang2017** [comment]
Hi,
1. It cost 12 hours on 8 GPUs.
2. Yes, it requires to search on the trained coco supernet.
3. The Supernet coco fine-tuned model is available at https://drive.google.com/open?id=1RPalJivbLeAAu7cLETrl45U6qEHQCX0K
