### ISSUE TITLE
Retinanet search

### ISSUE THREAD

**Issue by apxlwl** [megvii-model/DetNAS#9]
Hi, thank you for sharing the code. But I can't find the config file of retinanet_search. Could you upload it?

**Comment by yukang2017** [comment]
Hi,

thanks for your remind. I will update it in the next week.

**Comment by apxlwl** [comment]
@yukang2017 Hi, just want to remind you. :)

**Comment by yukang2017** [comment]
Sorry for the late reply!  I have updated it. 
If you have any further issues, please feel free to reopen this issues. You can also email me directly.

**Comment by apxlwl** [comment]
@yukang2017 Hi, Is COCO_RetinaNet_300M_supernet.pkl  the same with COCO_FPN_300M_supernet.pkl?  
另外，请问可以上传coco上训练好的完整supernet吗？ 我想直接尝试一下distributed_arch_search的过程。

**Comment by yuyijie1995** [comment]
@wlguan 你好你尝试成功了么
